# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10d011bd810b683c03f51f1e731dcc58f256a4e5880a6d95f3ea7f0b38fb8d1e8a9472b1c5851676e4ca8f0a137313d9b268e65c8a038692e13fdbecf2d93e2f

test:
  secret_key_base: 14db599714b85799c32ebe1d0c27a7be4fb04a71c627e8cedcc7bed44b91bbf487aa21b89c5a1c79017bac9a636c1930cc552080587ea10e5ad93dff51fe9686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
